Added module to deploy/undeploy JEE applications to the Glassfish application server
ansible/ansible-modules-extras pull request #1283
Opened 2015-11-25 01:18 UTC by NickMk

2015-11-25 01:19 UTC, NickMk commented
Ok, I see the error due to the lack of "with" in Python 2.4. I'll get that fixed...

2015-11-25 04:37 UTC, NickMk commented
I ostensibly made the necessary tweaks to get it to work under Python 2.4

2015-11-28 16:19 UTC, gregdek commented
Thanks @NickMk for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

2015-12-09 23:38 UTC, pilou- commented on web_infrastructure/glassfish_deploy.py
> +    except Exception, e:
This `try` statement is useless.

2017-04-10 09:42 UTC, 0mmariano requested changes
Can we hide the password provided?

Update this line --> url_password=   dict(required=True),
To this --> url_password=   dict(required=True, no_log=True),

Also, module doesn't look like it's idempotent. It returns a failure when you run the playbook again, with the application/war already deployed, even if you explicitly set force=false (default value). I would think it'll just skip over the deployment since the app is already deployed.

2017-04-10 09:47 UTC, closed without merging