re-write ec2_vpc_route_table.py to be Boto3 compatible
ansible/ansible-modules-extras pull request #1846
Opened 2016-03-12 03:53 UTC by linuxdynasty

##### Issue Type:

 - Feature Pull Request

##### Plugin Name:

ec2_vpc_route_table.py

##### Summary:
In the process of writing the ec2_vpc_nat_gateway.py, the ec2_vpc_route_table.py module would fail on subsequent runs. After further digging, Boto2 does not officially support Nat Gateways. This re-write of the module rips out Boto2 completely in place of Boto3. This module not officially supports all Amazon supported gateways. Also each function is heavily documented as well.

##### Example:

```
       [
            {
                "success": true,
                "changed": true,
                "msg": "Route table rtb-1234567 updated.",
                "associations": [
                    {
                        "subnet_id": "subnet-12345667",
                        "route_table_id": "rtb-1234567",
                        "main": false,
                        "route_table_association_id": "rtbassoc-1234567"
                    },
                    {
                        "subnet_id": "subnet-78654321",
                        "route_table_id": "rtb-78654321",
                        "main": false,
                        "route_table_association_id": "rtbassoc-78654321"
                    }
                ],
                "tags": [
                    {
                        "key": "Name",
                        "value": "dev_route_table"
                    },
                    {
                        "key": "env",
                        "value": "development"
                    }
                ],
                "routes": [
                    {
                        "gateway_id": "local",
                        "origin": "CreateRouteTable",
                        "state": "active",
                        "destination_cidr_block": "10.100.0.0/16"
                    },
                    {
                        "origin": "CreateRoute",
                        "state": "active",
                        "nat_gateway_id": "nat-12345678",
                        "destination_cidr_block": "0.0.0.0/0"
                    }
                ],
                "route_table_id": "rtb-1234567",
                "vpc_id": "vpc-1234567",
                "propagating_vgws": []
            }
        ]
```

* Rewrote the module to be Boto3 compatible.
* Documented every function.
* Supports all gateways (gateway_id, instance_id, network_interface_id, vpc_peering_connection_id, nat_gateway_id).

2016-03-14 15:29 UTC, gregdek commented
Thanks @linuxdynasty. To the current maintainers, @erydo, @wimnat please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

2016-03-17 10:18 UTC, wimnat commented
Unfortunately, i'm not sure what the core team will say about this. It breaks compatibility obviously.  @gregdek can you comment the core/aws guys here for input?

2016-03-17 14:36 UTC, linuxdynasty commented
@wimnat is is what the module is returning that breaks compatibility? Please let me know what aspect breaks it.

2016-03-28 07:12 UTC, wimnat commented
I mean that if someone didn't have boto3 installed on their system, it wouldn't run where as it could of been running fine before.

2016-03-28 15:10 UTC, linuxdynasty commented
How can this issue be resolved? I know I can make most of the api calls be Boto compliant. What I am concerned with is, that if we say this module works with Nat Gateways, and the user who is testing this module doesn't have Boto3 installed, then this module will still not work. Do I add an exception just for nat gateways, to try and import boto3 and only use the boto3 api for that particular call? Or do we just not support the adding of nat gateways in a route?

I just searched through the ansible-extra-modules/cloud/amazon for boto3 and I do not see in the code where both boto and boto3 is being used. I see that boto is being imported, but I do not see modules that are actually performing a boto api call when boto3 is not available and vice versa.

Also only new features like Nat Gateway are being added to Boto3 and not Boto. Does that mean, any existing modules can not support newer features, due to the chicken and the egg problem?

Please let me know on how to proceed.

2016-03-28 17:45 UTC, linuxdynasty commented
@sivel or @bcoca, may we get some guidance on how you guys think it is best to proceed with this PR?

2016-04-29 13:31 UTC, linuxdynasty commented
@gregdek, @sivel , @bcoca , how should we continue with this PR? Should I close it and we do not support Amazon Nat Gateways?

2016-04-29 15:37 UTC, gregdek commented
Moving to core review. I think that's most appropriate for now.

ping @ansible/core for input.

2016-07-08 04:27 UTC, gregdek commented
Thanks @linuxdynasty for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

2016-07-08 19:39 UTC, linuxdynasty commented
@gregdek, I have rebased against development.

2016-07-08 20:03 UTC, gregdek commented
Thanks @linuxdynasty. Putting back into core review.

2016-07-25 22:27 UTC, gregdek commented
Thanks @linuxdynasty for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

2016-08-10 10:27 UTC, gregdek commented
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-08-12 02:52 UTC, linuxdynasty commented
I am in the process of writing tests for this module.

2016-08-18 11:43 UTC, sgzijl commented
@linuxdynasty thanks for the PR. According to the module documentation, it should be possible to work with subnet names, but when providing a subnet name the module will fail with the following error msg:

`An error occurred (InvalidSubnetID.NotFound) when calling the AssociateRouteTable operation: The subnet ID 'subnet-a' does not exist`

If I run into other issues, I will report them shortly.

2016-08-18 14:27 UTC, linuxdynasty commented
@sgzijl thank you for catching that and I will update the tests accordingly.

2016-08-25 22:33 UTC, gregdek commented
@linuxdynasty Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

2016-08-30 16:59 UTC, ryansb commented
Is this rewrite going to allow legacy users to continue using boto with this module?

2016-08-30 17:28 UTC, linuxdynasty commented
@ryansb this rewrite will not. This is Boto3 only. If that is an issue, I can close this PR out.

2016-08-31 10:45 UTC, wimnat commented
I have brought this up before. At the Ansible 2.0 release, the core team specifically said they wanted to maintain compatibility with older boto modules but all new modules should be boto3.

Unless the core team have changed there stance then this module is cool, but perhaps not yet viable.

2016-08-31 17:14 UTC, ryansb commented
@linuxdynasty after talking this over with the core team, we wanted new modules after 2.0 to be in boto3, but weren't going to *rewrite* modules with boto3 until Ansible v2.3, which is in fact right around the corner. So keep this PR open, and once we start accepting 2.3 changes (in around a month) we'll be able to merge this change.

2016-08-31 17:14 UTC, ryansb commented
Also, this needs to be rebased in any event, so in a few weeks do the rebase and re-ping. Thanks! :)

2016-09-10 10:34 UTC, gregdek commented
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-25 22:35 UTC, gregdek commented
@linuxdynasty Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-11 10:27 UTC, gregdek commented
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-26 14:55 UTC, gregdek commented
Closing due to contributor inactivity.

2016-10-26 16:38 UTC, gregdek commented
Thanks @linuxdynasty for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-11 05:28 UTC, gregdek commented
@linuxdynasty A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-26 17:28 UTC, gregdek commented
@linuxdynasty Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-05 18:22 UTC, ryansb requested changes

2016-12-05 18:22 UTC, ryansb commented on cloud/amazon/ec2_vpc_route_table.py
> +version_added: "2.2"
I don't think this should be changed, since this isn't new in the 2.2/2.3 release.

2016-12-05 22:47 UTC, wimnat commented
@ryansb has the core team said we are allowed to rewrite modules to boto3 now we've hit 2.3?

2016-12-06 19:16 UTC, linuxdynasty commented on cloud/amazon/ec2_vpc_route_table.py
> +version_added: "2.2"
The reason I removed the other authors, was this was in fact a rewrite of the original module.

2016-12-06 19:16 UTC, linuxdynasty commented on cloud/amazon/ec2_vpc_route_table.py
> +version_added: "2.2"
I have no issues, re-adding them though.

2016-12-13 14:55 UTC, ryansb commented
@wimnat yes, that's correct. 

@linuxdynasty can you migrate this PR to the now-main `ansible/ansible` repo using [prmover](https://prmover.pythonanywhere.com/)?

2016-12-13 15:01 UTC, linuxdynasty commented
Sure thing AND YEAHHHHH BUDDDYYYYY BOTO3!!!!!

2017-04-11 23:11 UTC, closed without merging