added qemu_img module to interact with qemu-img
ansible/ansible-modules-extras pull request #2556
Opened 2016-07-13 14:16 UTC by toshywoshy

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
qemu_img

##### ANSIBLE VERSION
ansible 2.2.0 (devel 221520cbad) last updated 2016/07/13 10:20:35 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 67dadf3aa4) last updated 2016/07/13 10:20:40 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f2b255ffa3) last updated 2016/07/13 10:20:41 (GMT +200)

```

```

##### SUMMARY
This module is used to create qemu image files using the qemu-img command.
The module can create, resize (grow, shrink), and delete qemu image files

```

2016-07-13 16:25 UTC, gregdek commented
Thanks @toshywoshy for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-07-13 19:10 UTC, toshywoshy commented
@gregdek Now all checks have passed

2016-07-19 09:54 UTC, toshywoshy commented
ready_for_review

2016-07-19 10:25 UTC, gregdek commented
Thanks @toshywoshy for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-02 14:45 UTC, xen0l requested changes

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +  dest:
Could you add type: to every option? It would make it better for people to know what should the values be.

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +            dest=dict(type='str', required=True),
There is type='path', which you can use instead.

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +    description: The size of the image
What is the default unit for size? Comment would help here.

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +  - description: Enlarge the image to 6M.
Aren't you supposed to use state=resize here?

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +  dest:
Adding alias "path" would be good.

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +  options:
MIssing default value "preallocation=metadata".

2016-10-02 14:45 UTC, xen0l commented on cloud/misc/qemu_img.py
> +EXAMPLES = '''
Adding an example how to use this module with multiple options value here would be very helpful.

2017-02-08 10:59 UTC, closed without merging