Added new option to select the active a10 partition
ansible/ansible-modules-extras pull request #2628
Opened 2016-07-28 15:02 UTC by Babybolzer

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

a10
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY
Added new option to select the active a10 partition. 

```
No new output
```

2016-07-28 16:25 UTC, gregdek commented
Thanks @Babybolzer for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-07-28 21:56 UTC, Babybolzer commented
ready_for_review

2016-07-28 22:25 UTC, gregdek commented
Thanks @Babybolzer. To the current maintainers, @mischapeters please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-08-03 14:49 UTC, mischapeters commented
👍 shipit :shipit:

2016-08-03 16:25 UTC, gregdek commented
Thanks again to @Babybolzer for this PR, and thanks @mischapeters for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-08-04 07:19 UTC, resmo commented on network/a10/a10_server.py
> +msg:
this is a common return, please remove it from module description.

2016-08-04 07:19 UTC, resmo commented on network/a10/a10_service_group.py
> +msg:
this is a common return, please remove it from module description

2016-08-04 07:19 UTC, resmo commented on network/a10/a10_virtual_server.py
> +msg:
this is a common return, please remove it from module description

2016-08-11 10:21 UTC, gundalow commented on network/a10/a10_server.py
> +    aliases: []
Please remove empty options, this line (and similar isn't needed)

2016-08-11 10:23 UTC, gundalow commented on network/a10/a10_service_group.py
> +            partition=dict(type='str', aliases=['partition'], default=[]),
`partition` is the name, so you can remove `aliases=['partition'], `

2016-08-11 10:23 UTC, gundalow commented on network/a10/a10_virtual_server.py
> +            partition=dict(type='str', aliases=['partition'], default=[]),
`partition` is the name, so you can remove `aliases=['partition'], `

2016-08-11 10:24 UTC, gundalow commented on network/a10/a10_server.py
> +            partition=dict(type='str', aliases=['partition'], default=[]),
`partition` is the name, so you can remove `aliases=['partition'], `

2016-08-11 10:26 UTC, gundalow commented
1) You don't need to document empty cases, so the following lines can be removed from all modules
`aliases: []`

` choices: []`

2) Does the module still work if you don't specify `partition`?

needs_revision

2016-08-11 16:25 UTC, gregdek commented
Thanks @Babybolzer for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-08-19 07:44 UTC, Babybolzer commented
@gundalow thanks for the input. Yes, the module still works without specifying `partition`. The changes are then simply done to the default partition.

2016-08-19 07:44 UTC, Babybolzer commented
ready_for_review

2016-08-19 10:25 UTC, gregdek commented
Thanks @Babybolzer. To the current maintainers, @mischapeters please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-25 16:33 UTC, gregdek commented
Thanks @Babybolzer for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

2016-11-10 05:27 UTC, gregdek commented
@Babybolzer A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-21 19:54 UTC, Babybolzer commented
ready_for_review

2016-11-21 23:27 UTC, gregdek commented
Thanks @Babybolzer. To the current maintainers, @mischapeters please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-22 08:02 UTC, mischapeters commented
shipit

2016-11-22 11:27 UTC, gregdek commented
Thanks again to @Babybolzer for this PR, and thanks @mischapeters for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 23:30 UTC, gregdek commented
Thanks @Babybolzer for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

2016-11-25 08:13 UTC, gundalow requested changes
needs_revision

2016-11-25 08:13 UTC, gundalow commented on network/a10/a10_server.py
> +  host:
Hi,
You don't need to document host, username, or password as the are documented in https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/module_docs_fragments/a10.py

Which is pulled in by `extends_documentation_fragment: a10`

2016-11-25 08:13 UTC, gundalow commented on network/a10/a10_service_group.py
> +  host:
Please remove host, username, and password.

2016-11-25 08:13 UTC, gundalow commented on network/a10/a10_service_group.py
> +  write_config:
Please remove write_config and validate_certs

2016-11-25 08:13 UTC, gundalow commented on network/a10/a10_virtual_server.py
> +  host:
Please remove host, username, and password.

2016-11-25 13:35 UTC, gundalow commented on network/a10/a10_service_group.py
> +  write_config:
Just checking you saw that `write_config` and `validate_certs` docs need removing as well

2016-11-29 16:34 UTC, Babybolzer commented
ready_for_review

2016-11-29 17:28 UTC, gregdek commented
Thanks @Babybolzer. To the current maintainers, @mischapeters, @ericchou1, @gundalow, @qalthos, @privateip please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-30 15:08 UTC, gundalow approved these changes

2016-11-30 15:08 UTC, merged