Added set value to openvswitch_bridge
ansible/ansible-modules-extras pull request #2711
Opened 2016-08-10 18:32 UTC by galexrt

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
openvswitch_bridge

##### ANSIBLE VERSION
```
2.1.1.0
```

##### SUMMARY
This allow to set options for openvswitch bridges like the openvswitch_ports module already allows us to do.

2016-08-10 22:25 UTC, gregdek commented
Thanks @galexrt. To the current maintainers, @stygstra please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-25 10:26 UTC, gregdek commented
Thanks @galexrt for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

2016-10-31 12:47 UTC, galexrt commented
ready_for_review

2016-10-31 21:58 UTC, ghost requested changes
Thanks! A couple small changes and it'll be ready to go.

2016-10-31 21:58 UTC, ghost commented on network/openvswitch_bridge.py
> +        self.set_opt = module.params.get('set', None)
Could you add `'set'` to the `argument_spec` in `main()`?

``` python
            'set': {'required': False, 'default': None},
```

2016-10-31 21:58 UTC, stygstra commented on network/openvswitch_bridge.py
> +    set_cmd = truncate_before(set_cmd, " option:")
`truncate_before` appears to be undefined. Here's how it was defined in `openvswitch_port` if you want to copy that over:

```python
def truncate_before(value, srch):
    """ Return content of str before the srch parameters. """

    before_index = value.find(srch)
    if (before_index >= 0):
        return value[:before_index]
    else:
        return value
```

2016-10-31 22:06 UTC, galexrt commented on network/openvswitch_bridge.py
> +        self.set_opt = module.params.get('set', None)
Done.

2016-10-31 22:06 UTC, galexrt commented on network/openvswitch_bridge.py
> +    set_cmd = truncate_before(set_cmd, " option:")
I copied it.

2016-11-01 02:27 UTC, ghost approved these changes

2016-11-01 02:28 UTC, stygstra commented
@galexrt Thanks!

@gregdek shipit

2016-11-08 05:27 UTC, gregdek commented
Thanks again to @galexrt for this PR, and thanks @stygstra for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2017-01-03 10:01 UTC, gundalow commented
https://github.com/ansible/ansible/pull/19692 has been merged, so closing this

2017-01-03 10:01 UTC, closed without merging