Adding "File" Attribute for Upload Files
ansible/ansible-modules-extras pull request #3008
Opened 2016-09-22 15:20 UTC by blakfeld

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
win_uri

##### SUMMARY
This is to address Issue #2999.

User was attempting to upload a file using the "body" attribute. This
resulted in a zero length file being uploaded. This solution here:

https://www.jfrog.com/knowledge-base/how-do-i-execute-a-file-upload-via-powershell/

Says to use the "-InFile" flag for Invoke-WebRequest.

I added a "file" attribute that, when specified, sets that "-InFile"
flag.

2016-09-22 16:25 UTC, gregdek commented
Thanks @blakfeld for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-08 04:27 UTC, gregdek commented
@blakfeld A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-23 16:26 UTC, gregdek commented
@blakfeld Another friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open. If you have addressed the issues and believe it's ready for review, please comment with the text "ready_for_review". If we don't hear from you within another 14 days, we will close this pull request.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-25 14:42 UTC, blakfeld commented
I think I'm missing something. I'm trying to see why the build failed, but the console output is blank. Can anyone clue me in on what's choking everything up?

2016-11-08 05:26 UTC, gregdek commented
@blakfeld A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 15:33 UTC, blakfeld commented
@gregdek I have no idea why the build is failing. Any suggestions? I don't see anything helpful in the logs, but it's likely I don't know where to look.

2016-11-08 16:01 UTC, gregdek commented
Hmmm... https://app.shippable.com/runs/5821ef0001c1f10e00ad9db2/17/console

Kind of looks like an error in the CI code itself?

I'm gonna guess bot_broken on this one. Maybe @mattclay can weigh in.

2016-11-09 08:50 UTC, mattclay commented
@blakfeld, @gregdek: I've fixed the bug in validate-modules which was masking the actual error.

The problem is with [this line](https://github.com/ansible/ansible-modules-extras/pull/3008/files#diff-36924c372fb511ab75507685c45a0099R132):

```
    sample: "C:\some\file\path"
```

The `\f` is parsed as a form feed by python, which is causing the error. Use `/` instead of `\` for paths to avoid this issue.

2016-11-09 08:52 UTC, mattclay requested changes

2016-11-09 08:52 UTC, mattclay commented on windows/win_uri.py
> +    file: C:\some\file\path.zip
Use `/` instead of `\` for paths to avoid parsing issues.

2016-11-09 08:52 UTC, mattclay commented on windows/win_uri.py
> +    sample: "C:\some\file\path"
Use `/` instead of `\` for paths to avoid parsing issues.

2016-11-09 16:28 UTC, mattclay approved these changes

2016-11-09 16:32 UTC, mattclay commented
@blakfeld The new `file` option requires `version_added`, as reported here:

https://app.shippable.com/runs/58234408c857350e00b60a83/17/console

2016-11-09 17:12 UTC, blakfeld commented
Thanks for the catch @mattclay! I figured I was doing something silly, but I just couldn't figure out what!

2016-11-09 22:09 UTC, blakfeld commented
ready_for_review

2016-11-09 23:29 UTC, gregdek commented
Thanks @blakfeld. To the current maintainers, @blakfeld please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-09 23:36 UTC, blakfeld commented
shipit

2016-11-10 05:26 UTC, gregdek commented
Thanks @blakfeld. Since you are one of the maintainers (@blakfeld) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2017-04-11 23:07 UTC, closed without merging