consul_kv read configuration from consul
ansible/ansible-modules-extras pull request #3019
Opened 2016-09-23 09:31 UTC by raben2

#####

    Feature Pull Request

COMPONENT NAME

clustering/consul_kv.py
ANSIBLE VERSION

ansible 2.2.0
config file = /etc/ansible/ansible.cfg
configured module search path = ['/home/work/scripts/ansible-modules/*']
SUMMARY

added module state 'read' to obtain information from consul key value store
example:

    name: Read from consul key consul_kv key: test/key1 state: read

output:

ok: [localhost] => {
"msg": {
"changed": true,
"data": {
"CreateIndex": 370684,
"Flags": 0,
"Key": "test/key1",
"LockIndex": 0,
"ModifyIndex": 379139,
"Value": "SomeValueFromKeystore "
},
"index": "379139",
"key": "FFB/stage/versions"
}
}

2016-09-23 10:25 UTC, gregdek commented
Thanks @raben2. To the current maintainers, @sgargan please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-09-24 10:02 UTC, sgargan commented on clustering/consul_kv.py
> +  session = module.params.get('session')
⚡ the session as its not used.

2016-09-24 10:03 UTC, sgargan commented on clustering/consul_kv.py
> +  consul_api = get_consul_api(module)
indent 4 to be consistent.

2016-09-24 10:07 UTC, sgargan commented on clustering/consul_kv.py
> +     module.fail_json(msg="something went wrong: %s" % e)
Would be good to have some context in the error message
```python
module.fail_json(msg="Error reading '%s' key from consul: %s" % (key, e))
```

2016-09-24 10:07 UTC, sgargan commented on clustering/consul_kv.py
> +  module.exit_json(changed=changed,
just inline the change here

2016-09-24 10:13 UTC, sgargan requested changes
This is great @raben2 thanks for taking the time to add it. I've a couple of very minor comments. 

If you're feeling diligent, there are tests in the core project (here)[https://github.com/ansible/ansible/blob/devel/test/integration/roles/test_consul_kv/tasks/main.yml] would be awesome to get one for your read function in there too.

2016-09-25 18:52 UTC, raben2 commented on clustering/consul_kv.py
> +  module.exit_json(changed=changed,
thank you for the additions!

2016-11-08 11:26 UTC, gregdek commented
Thanks @raben2 for this PR. Unfortunately, it is not mergeable in its current state due to merge conflicts. Please rebase your PR. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

For help on how to do this cleanly please see http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes

[This message brought to you by your friendly Ansibull-bot.]

2016-11-23 23:26 UTC, gregdek commented
@raben2 A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-09 08:21 UTC, closed without merging