Stress module
ansible/ansible-modules-extras pull request #3107
Opened 2016-10-06 17:11 UTC by bbyhuy

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME
stress

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Benchmarking is a field which automation is often sought after. By wrapping these benchmark tools (more to come) as Ansible modules, it enables people to quickly launch benchmarks remotely and at scale. Each benchmark module is formatted with essentially the same boilerplate with specific changes to just the parsing and execution portions. As much of the code is kept the same as possible as to allow adding new benchmarks to be quick and painless.

stress is a deliberately simple workload generator for POSIX systems. It imposes a configurable amount of CPU, memory, I/O, and disk stress on the system.

2016-10-06 22:25 UTC, gregdek commented
Thanks @bbyhuy for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-30 10:58 UTC, haad requested changes

2016-10-30 10:58 UTC, haad commented on benchmarks/stress.py
> +     - change working directory
Generally option entries in doc should be written as sentence.

2016-10-30 10:58 UTC, haad commented on benchmarks/stress.py
> +- stress: timeout=10 cpu=1
Can you use ansible native YAML syntax here ? it considered best practice for new modules.

2016-10-30 10:58 UTC, haad commented on benchmarks/stress.py
> +            stress_bin = module.get_bin_path('stress', True, ['/usr/bin/local'])
/usr/bin/local looks like very specific path ? can we use standard system PATH in case if path is not specified or maybe /usr/local/bin ?

2016-11-03 17:15 UTC, bbyhuy commented on benchmarks/stress.py
> +            stress_bin = module.get_bin_path('stress', True, ['/usr/bin/local'])
I believe that parameter is opt_dirs which just adds '/usr/bin/local' to the list of pre-defined paths to search. So I don't think there should be too much of a problem here.

[https://github.com/ansible/ansible/blob/fda933723c8cb60248d41b5691edd86fe0a40807/lib/ansible/module_utils/basic.py#L1723-L1728]

2016-12-16 21:00 UTC, closed without merging