Add ovirt_datacenters and ovirt_datacenters_facts modules
ansible/ansible-modules-extras pull request #3146
Opened 2016-10-12 11:48 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

 - ovirt_datacenters
 - ovirt_datacenters_facts

##### ANSIBLE VERSION

```
ansible 2.1.1.0
```

##### SUMMARY

Add ovirt_datacenters and ovirt_datacenters_facts modules to manage oVirt datacenters.

```

```

2016-10-12 13:12 UTC, machacekondra commented
@mwperina @ryansb

2016-10-12 13:12 UTC, machacekondra commented
ready_for_review

2016-10-12 16:25 UTC, gregdek commented
Thanks @machacekondra for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-14 10:03 UTC, machacekondra commented
shipit

2016-10-14 10:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 10:37 UTC, mwperina requested changes

2016-10-19 10:37 UTC, mwperina commented on cloud/ovirt/ovirt_datacenters.py
> +    compatibility_version: 4.1
Please use version 4.0, as 4.1 may not be released before Ansible 2.3

2016-10-19 10:44 UTC, mwperina commented on cloud/ovirt/ovirt_datacenters_facts.py
> +# Gather facts about all datacenters named C<production*>:
I'd rephrase to: 'Gather facts about all data centers which names start with C<production>:'

2016-10-19 10:47 UTC, mwperina requested changes
Generally looks good, just 2 small doc issues

2016-10-20 10:46 UTC, mwperina requested changes

2016-10-20 10:46 UTC, mwperina commented on cloud/ovirt/ovirt_datacenters_facts.py
> +# Gather facts about all data centers which names start with C<production*>:
'C(production*)' -> 'C(production)'

2016-10-20 19:26 UTC, mwperina requested changes

2016-10-20 19:26 UTC, mwperina commented on cloud/ovirt/ovirt_datacenters_facts.py
> +# Gather facts about all data centers which names start with C<production>:
`C<production>` -> `C(production)`

2016-10-21 09:56 UTC, machacekondra commented on cloud/ovirt/ovirt_datacenters_facts.py
> +# Gather facts about all data centers which names start with C<production>:
done

2016-10-21 11:36 UTC, mwperina approved these changes
Looks good to me, thanks!

2016-11-08 05:26 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 21:48 UTC, ryansb commented on cloud/ovirt/ovirt_datacenters.py
> +    import ovirtsdk4.types as otypes
Please add a conditional on these (similar to the AWS modules) so your module doesn't raise ImportError at load.

2016-11-08 21:51 UTC, ryansb commented
Looks good overall, just add a failure mode for when the oVirt SDK isn't installed.

2016-11-22 14:59 UTC, machacekondra commented
shipit

2016-11-22 17:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 14:18 UTC, mwperina approved these changes
:+1:

2016-12-05 17:31 UTC, merged