Add ovirt_networks and ovirt_networks_facts modules
ansible/ansible-modules-extras pull request #3148
Opened 2016-10-12 12:58 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- ovirt_networks 
- ovirt_networks_facts

##### ANSIBLE VERSION

```
ansible 2.1.1.0
```

##### SUMMARY

This PR adds ovirt_networks and ovirt_networks_facts modules to manage oVirt logical networks.

```

```

2016-10-12 13:12 UTC, machacekondra commented
@mwperina @ryansb

2016-10-12 13:12 UTC, machacekondra commented
ready_for_review

2016-10-12 16:25 UTC, gregdek commented
Thanks @machacekondra for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-14 10:03 UTC, machacekondra commented
shipit

2016-10-14 10:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 10:49 UTC, mwperina requested changes

2016-10-19 10:49 UTC, mwperina commented on cloud/ovirt/ovirt_networks.py
> +    auth: "{{ ovirt_auth }}"
Please remove auth parameter to be consistent with other modules and examples note

2016-10-19 10:49 UTC, mwperina commented on cloud/ovirt/ovirt_networks_facts.py
> +# Gather facts about all networks named C<vlan1*>:
I'd rephrase to 'Gather facts about all networks which names start with C<vlan1>:

2016-10-20 10:44 UTC, mwperina requested changes

2016-10-20 10:44 UTC, mwperina commented on cloud/ovirt/ovirt_networks_facts.py
> +# Gather facts about all networks which names start with C(vlan1*):
'C(vlan1*)' -> 'C(vlan1)'

2016-10-20 19:24 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-11-08 01:19 UTC, bcoca commented
so most of the  modules seem to have same issues as on the ticket i've already commented on, I'm going to remove shipit from all of them until the first ticket gets through.

FYI, we normally require an initial ticket for 1 module as it allows us to debug any systemic issues before you submit the rest.

2016-11-08 05:26 UTC, gregdek commented
Thanks again to @machacekondra for this PR. This PR was reviewed by an Ansible member. Marking for inclusion.

However, we would still appreciate if the maintainer(s) @machacekondra could look over it.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 08:52 UTC, machacekondra commented
Will fix. There are already three modules merged:

 https://github.com/ansible/ansible-modules-extras/pull/2836

2016-11-22 14:55 UTC, machacekondra commented
shipit

2016-11-24 14:17 UTC, mwperina approved these changes
:+1:

2016-12-05 17:32 UTC, merged