Add oVirt users/groups and users_facts/group/facts modules
ansible/ansible-modules-extras pull request #3153
Opened 2016-10-13 07:39 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ovirt_groups
ovirt_groups_facts
ovirt_users
ovirt_users_facts

##### ANSIBLE VERSION

```
ansible 2.1.2.0
```

##### SUMMARY

This PR adds new oVirt modules for managing users and groups in oVirt and also add modules for retriving facts about groups and users.

```

```

2016-10-13 08:20 UTC, machacekondra commented
ready_for_review

2016-10-13 10:25 UTC, gregdek commented
Thanks @machacekondra for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-13 15:15 UTC, machacekondra commented
@mwperina @ryansb

2016-10-14 10:04 UTC, machacekondra commented
shipit

2016-10-14 10:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 11:08 UTC, mwperina requested changes

2016-10-19 11:08 UTC, mwperina commented on cloud/ovirt/ovirt_groups_facts.py
> +# Gather facts about all groups stars on string C<admin*>:
I'd rephrase to: 'Gather facts about all groups which names start with C<admin>:'

2016-10-19 11:08 UTC, mwperina commented on cloud/ovirt/ovirt_users.py
> +            user_name='{}@{}'.format(
Please extract username formatting into a method and reuse this method.

2016-10-19 11:08 UTC, mwperina commented on cloud/ovirt/ovirt_users.py
> +                    'usrname': '{}@{}'.format(
Please extract username formatting into a method and reuse this method.

2016-10-19 11:08 UTC, mwperina commented on cloud/ovirt/ovirt_users.py
> +                search_params={
Please extract username formatting into a method and reuse this method.

2016-10-19 11:08 UTC, mwperina commented on cloud/ovirt/ovirt_users_facts.py
> +# Gather facts about all users stars on string C<john*>:
I'd rephrase to: 'Gather facts about all users which first names start with C<john>:'

2016-10-20 10:43 UTC, mwperina requested changes

2016-10-20 10:43 UTC, mwperina commented on cloud/ovirt/ovirt_groups_facts.py
> +# Gather facts about all groups which names start with C(admin*):
'C(admin*)' -> 'C(admin)'

2016-10-20 10:43 UTC, mwperina commented on cloud/ovirt/ovirt_users_facts.py
> +# Gather facts about all users stars on string C<john*>:
I'd rephrase to: 'Gather facts about all users which first names start with C(john):'

2016-10-20 19:23 UTC, mwperina requested changes

2016-10-20 19:23 UTC, mwperina commented on cloud/ovirt/ovirt_users_facts.py
> +# Gather facts about all users stars on string C<john>:
Please rephrase: 'Gather facts about all users which names start with C(john):'

2016-10-21 09:56 UTC, machacekondra commented on cloud/ovirt/ovirt_users_facts.py
> +# Gather facts about all users stars on string C<john>:
done

2016-10-21 11:35 UTC, mwperina requested changes

2016-10-21 11:35 UTC, mwperina commented on cloud/ovirt/ovirt_users_facts.py
> +# Gather facts about all users stars on string C(john):
Please rephrase to: 'Gather facts about all users which first names start with C(john):'

2016-10-25 18:00 UTC, machacekondra commented on cloud/ovirt/ovirt_users_facts.py
> +# Gather facts about all users stars on string C(john):
done

2016-10-25 18:00 UTC, machacekondra commented
shipit

2016-10-25 21:37 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-11-08 05:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-22 14:47 UTC, machacekondra commented
shipit

2016-11-24 14:16 UTC, mwperina approved these changes
:+1:

2016-12-05 17:32 UTC, merged