Add oVirt ovirt_permissions and ovirt_permissions_facts modules
ansible/ansible-modules-extras pull request #3160
Opened 2016-10-13 15:01 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

 - ovirt_permissions
 - ovirt_permissions_facts

##### SUMMARY

This PR adds two new modules for managing permissions in oVIrt.

2016-10-13 16:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-14 10:04 UTC, machacekondra commented
@mwperina @ryansb

2016-10-14 10:04 UTC, machacekondra commented
shipit

2016-10-14 10:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 11:11 UTC, mwperina requested changes

2016-10-19 11:11 UTC, mwperina commented on cloud/ovirt/ovirt_permissions_facts.py
> +# Gather facts about all permissions of user john:
I'd rephrase: 'Gather facts about all permissions of user with username C<john>:'

2016-10-20 10:39 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-25 17:57 UTC, machacekondra commented
shipit

2016-11-08 05:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 22:17 UTC, ryansb commented on cloud/ovirt/ovirt_permissions.py
> +    import ovirtsdk4.types as otypes
Same comment - please look at how the AWS modules handle these imports to surface errors to users.

2016-11-08 22:18 UTC, ryansb commented
Looks good, other than the import statement

2016-11-22 14:36 UTC, machacekondra commented
shipit

2016-11-24 14:16 UTC, mwperina approved these changes
:+1:

2016-12-05 17:43 UTC, merged