Add oVirt ovirt_vmpools and ovirt_vmpools_facts modules
ansible/ansible-modules-extras pull request #3171
Opened 2016-10-14 12:46 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- ovirt_vmpools
- ovirt_vmpools_facts

##### SUMMARY

This PR adds two new modules for manage VM pools in oVirt.

2016-10-14 12:58 UTC, machacekondra commented
@mwperina @ryansb

2016-10-14 16:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 11:23 UTC, mwperina requested changes

2016-10-19 11:23 UTC, mwperina commented on cloud/ovirt/ovirt_vmpools_facts.py
> +# Gather facts about all vmpools named C<rhel*>:
I'd rephrase to: 'Gather facts about all vm pools which names start with C<centos>:'

2016-10-19 11:36 UTC, mwperina commented on cloud/ovirt/ovirt_vmpools_facts.py
> +    pattern: name=rhel*
rhel -> centos

2016-10-20 10:38 UTC, mwperina requested changes

2016-10-20 10:38 UTC, mwperina commented on cloud/ovirt/ovirt_vmpools_facts.py
> +# Gather facts about all vm pools which names start with C(centos*):
'C(centos*)' -> 'C(centos)'

2016-10-20 19:21 UTC, mwperina approved these changes
Looks good to me, thank! :+1:

2016-10-25 17:57 UTC, machacekondra commented
shipit

2016-10-25 22:27 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:26 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-22 14:12 UTC, machacekondra commented
shipit

2016-11-22 17:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 14:15 UTC, mwperina approved these changes
:+1:

2016-12-05 17:43 UTC, merged