Add parameter hash_host
ansible/ansible-modules-extras pull request #3204
Opened 2016-10-17 12:42 UTC by psykotox

##### ISSUE TYPE
 - Feature Pull Request
 
##### COMPONENT NAME
known_hosts

##### ANSIBLE VERSION
```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
Add the possibility to hash the hostname of the key in the known_hosts file. Or disable the hash of a specific hostname.

2016-10-17 16:25 UTC, gregdek commented
Thanks @psykotox. To the current maintainers, @mcv21 please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-17 16:31 UTC, psykotox commented
Shipit

2016-10-18 08:30 UTC, mcv21 requested changes
I'm happy with this; can you tidy up the tab you added? Thanks :)

2016-10-18 08:30 UTC, mcv21 commented on system/known_hosts.py
> +
spurious whitespace introduced?

2016-10-18 09:04 UTC, mcv21 commented
shipit

2016-10-18 10:25 UTC, gregdek commented
Thanks again to @psykotox for this PR, and thanks @mcv21 for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-07 21:18 UTC, merged