Add oVirt ovirt_nics and ovirt_nics_facts modules
ansible/ansible-modules-extras pull request #3205
Opened 2016-10-17 13:21 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request<

##### COMPONENT NAME

 - ovirt_nics
 - ovirt_nics_facts

##### SUMMARY

This PR adds two new modules for managing VM's network interfaces.

2016-10-17 13:28 UTC, machacekondra commented
@mwperina @ryansb

2016-10-17 16:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 11:29 UTC, mwperina requested changes
I'd also replace 'Virtual Machine' with 'VM' to be consistent but not a must

2016-10-19 11:29 UTC, mwperina commented on cloud/ovirt/ovirt_nics_facts.py
> +# Gather facts about all NICs named C<eth*>:
I'd rephrase to: 'Gather facts about all NICs which names start with C<eth>:'

2016-10-20 10:37 UTC, mwperina requested changes

2016-10-20 10:37 UTC, mwperina commented on cloud/ovirt/ovirt_nics_facts.py
> +# Gather facts about all NICs which names start with C(eth*):
'C(eth*)' -> 'C(eth)'

2016-10-20 19:19 UTC, mwperina requested changes

2016-10-20 19:19 UTC, mwperina commented on cloud/ovirt/ovirt_nics_facts.py
> +# Gather facts about all NICs which names start with C(eth):
I forgot that vm name is also specified, so the comment should be:

Gather facts about all NICs which names start with C(eth) for VM named C(centos7)

2016-10-20 19:19 UTC, mwperina commented on cloud/ovirt/ovirt_nics_facts.py
> +    vm: rhel7
'rhel7' -> 'centos7'

2016-10-21 09:56 UTC, machacekondra commented on cloud/ovirt/ovirt_nics_facts.py
> +    vm: rhel7
done

2016-10-21 09:56 UTC, machacekondra commented on cloud/ovirt/ovirt_nics_facts.py
> +# Gather facts about all NICs which names start with C(eth):
done

2016-10-21 11:32 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-25 17:57 UTC, machacekondra commented
shipit

2016-10-25 22:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-18 14:24 UTC, ryansb commented on cloud/ovirt/ovirt_nics_facts.py
> +        module.fail_json(msg=str(e))
Same here, please surface the full exception.

2016-11-18 14:24 UTC, ryansb commented on cloud/ovirt/ovirt_nics.py
> +        module.fail_json(msg=str(e))
Same here, please surface the full exception.

2016-11-22 13:04 UTC, machacekondra commented
shipit

2016-11-22 17:26 UTC, gregdek commented
Thanks @machacekondra for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-23 10:09 UTC, machacekondra commented
shipit

2016-11-23 11:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 14:14 UTC, mwperina approved these changes
:+1:

2016-12-05 17:42 UTC, merged