Add oVirt ovirt_templates and ovirt_templates_facts modules
ansible/ansible-modules-extras pull request #3221
Opened 2016-10-18 11:59 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- ovirt_templates
- ovirt_templates_facts

##### SUMMARY

This PR adds new modules for managing oVirt templates.

2016-10-18 12:14 UTC, machacekondra commented
@mwperina @ryansb

2016-10-18 16:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 11:36 UTC, mwperina requested changes

2016-10-19 11:36 UTC, mwperina commented on cloud/ovirt/ovirt_templates.py
> +    - "Module to manage virtual machine templates in oVir."
oVir -> oVirt

2016-10-19 11:36 UTC, mwperina commented on cloud/ovirt/ovirt_templates.py
> +    - "Module to manage virtual machine templates in oVir."
virtual machine -> VM

2016-10-19 11:36 UTC, mwperina commented on cloud/ovirt/ovirt_templates_facts.py
> +extends_documentation_fragment: ovirt
ovirt -> oVirt

2016-10-19 11:36 UTC, mwperina commented on cloud/ovirt/ovirt_templates_facts.py
> +# Gather facts about all templates named C<rhel**> from datacenter C(west):
I'd rephrase to: 'Gather facts about all templates which names start with C<centos> and belongs to data center C(west):'

2016-10-19 11:36 UTC, mwperina commented on cloud/ovirt/ovirt_templates_facts.py
> +    pattern: name=rhel* and datacenter=west
rhel -> centos

2016-10-20 10:34 UTC, mwperina requested changes

2016-10-20 10:34 UTC, mwperina commented on cloud/ovirt/ovirt_templates_facts.py
> +# Gather facts about all templates which names start with C(centos*) and belongs to data center C(west):
'C(centos*)' -> 'C(centos)'

2016-10-20 19:11 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-25 17:57 UTC, machacekondra commented
shipit

2016-10-25 22:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-18 14:24 UTC, ryansb commented on cloud/ovirt/ovirt_templates.py
> +        module.fail_json(msg=str(e))
Same here, please surface the full exception.

2016-11-18 14:24 UTC, ryansb commented on cloud/ovirt/ovirt_templates_facts.py
> +        module.fail_json(msg=str(e))
Same here, please surface the full exception.

2016-11-23 10:09 UTC, machacekondra commented
shipit

2016-11-23 11:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 14:13 UTC, mwperina approved these changes
:+1:

2016-12-05 17:37 UTC, ryansb commented on cloud/ovirt/ovirt_templates_facts.py
> +extends_documentation_fragment: ovirt
@mwperina Lower case is the correct reference.

2016-12-05 17:37 UTC, merged