Add oVirt ovirt_storage_domains and ovirt_storage_domains_facts modules
ansible/ansible-modules-extras pull request #3222
Opened 2016-10-18 13:41 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

 - ovirt_storage_domains
 - ovirt_storage_domains_facts

##### SUMMARY

This PR adds new modules to manage storage domains in oVirt.

2016-10-18 16:25 UTC, gregdek commented
Thanks @machacekondra for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 14:17 UTC, machacekondra commented
@mwperina @ryansb

2016-10-20 10:31 UTC, mwperina requested changes

2016-10-20 10:31 UTC, mwperina commented on cloud/ovirt/ovirt_storage_domains.py
> +            - "Datacenter name where storage domain should be attached."
Datacenter -> Data center

2016-10-20 10:31 UTC, mwperina commented on cloud/ovirt/ovirt_storage_domains_facts.py
> +# Gather facts about all storage domains named C<data**> from datacenter C(west):
I'd rephrase to: 'Gather facts about all storage domains which names start with C<data> and belong to data center C(west):'

2016-10-20 19:10 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-25 17:56 UTC, machacekondra commented
shipit

2016-10-25 22:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-18 14:24 UTC, ryansb commented on cloud/ovirt/ovirt_storage_domains.py
> +        module.fail_json(msg=str(e))
Same here, please surface the full exception.

2016-11-18 14:24 UTC, ryansb commented on cloud/ovirt/ovirt_storage_domains_facts.py
> +        module.fail_json(msg=str(e))
Same here, please surface the full exception.

2016-11-22 12:38 UTC, machacekondra commented
shipit

2016-11-22 17:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 14:12 UTC, mwperina approved these changes
:+1:

2016-12-05 17:35 UTC, merged