Add oVirt ovirt_hosts and ovirt_storage_hosts_facts modules
ansible/ansible-modules-extras pull request #3225
Opened 2016-10-18 15:15 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

 - ovirt_hosts
 - ovirt_hosts_facts

##### SUMMARY

This PR adds new modules for managing hosts in oVirt.

2016-10-18 16:25 UTC, gregdek commented
Thanks @machacekondra for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 14:17 UTC, machacekondra commented
@mwperina @ryansb

2016-10-20 10:26 UTC, mwperina requested changes

2016-10-20 10:26 UTC, mwperina commented on cloud/ovirt/ovirt_hosts.py
> +            - "Should the host be present/absent/maintenance/upgraded"
I'd rephrase to: 'State which should a host to be in after successful completion'

2016-10-20 10:26 UTC, mwperina commented on cloud/ovirt/ovirt_hosts.py
> +            - "Host address. Can be IP address or FQDN."
I'd rephrase to: 'Host address. It can be either FQDN (preferred) or IP address.'

2016-10-20 10:26 UTC, mwperina commented on cloud/ovirt/ovirt_hosts_facts.py
> +# Gather facts about all hosts named C<host**> from datacenter C(west):
I'd rephrase to: 'Gather facts about all hosts which names start with C<host> and belong to data center C(west):

2016-10-20 19:09 UTC, mwperina requested changes

2016-10-20 19:09 UTC, mwperina commented on cloud/ovirt/ovirt_hosts.py
> +            - "Should the host be present/absent/maintenance/upgraded"
Please rephrase as suggested

2016-10-21 09:56 UTC, machacekondra commented on cloud/ovirt/ovirt_hosts.py
> +            - "Should the host be present/absent/maintenance/upgraded"
done

2016-10-21 11:30 UTC, mwperina approved these changes
Looks good to me, thanks!

2016-10-25 17:56 UTC, machacekondra commented
shipit

2016-10-25 22:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-18 14:23 UTC, merged