Add oVirt ovirt_vms_facts module
ansible/ansible-modules-extras pull request #3226
Opened 2016-10-18 16:32 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

- ovirt_vms_facts

##### SUMMARY

This PR adds new _ovirt_vms_facts_ module, which handle facts about oVirt virtual machines.

2016-10-18 22:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-19 14:17 UTC, machacekondra commented
@mwperina @ryansb

2016-10-20 10:06 UTC, mwperina requested changes

2016-10-20 10:06 UTC, mwperina commented on cloud/ovirt/ovirt_vms_facts.py
> +# Gather facts about all VMs named C<rhel**> from cluster C(west):
I'd rephrase to: 'Gather facts about all VMs which names start with C<centos> and belong to cluster C(west):'

2016-10-20 10:06 UTC, mwperina commented on cloud/ovirt/ovirt_vms_facts.py
> +    pattern: name=rhel* and cluster=west
rhel -> centos

2016-10-20 19:07 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-25 17:56 UTC, machacekondra commented
shipit

2016-10-25 22:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-18 14:18 UTC, ryansb commented on cloud/ovirt/ovirt_vms_facts.py
> +        module.fail_json(msg=str(e))
Can you add the exception to the failure here, such as:

```
try:
    # stuff
except Exception as e:
    import traceback
    module.fail_json(msg=str(e), exception=traceback.format_exc())
```

2016-11-22 10:03 UTC, machacekondra commented on cloud/ovirt/ovirt_vms_facts.py
> +        module.fail_json(msg=str(e))
done

2016-11-22 10:03 UTC, machacekondra commented
shipit

2016-11-22 11:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 14:11 UTC, mwperina approved these changes
:+1:

2016-12-05 17:34 UTC, merged