Add oVirt ovirt_host_networks modules
ansible/ansible-modules-extras pull request #3227
Opened 2016-10-18 16:57 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

 - ovirt_host_networks

##### SUMMARY

This PR adds new module to manage networks of the hosts in oVirt.

2016-10-18 22:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-20 12:44 UTC, machacekondra commented
@mwperina

2016-10-20 14:00 UTC, mwperina requested changes

2016-10-20 14:00 UTC, mwperina commented on cloud/ovirt/ovirt_host_networks.py
> +            - "Name of the the host to manage networks."
I'd rephrase: 'Name of the the host to manage networks for.'

2016-10-20 14:00 UTC, mwperina commented on cloud/ovirt/ovirt_host_networks.py
> +               is lost changes are rolled back."
I'd rephrase:

Network configuration changes will be rolled back if connectivity between engine and the host is lost after changing network configuration.

2016-10-20 19:06 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-25 17:56 UTC, machacekondra commented
shipit

2016-10-25 22:26 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-18 14:16 UTC, merged