Add oVirt ovirt_host_pm module
ansible/ansible-modules-extras pull request #3253
Opened 2016-10-20 12:43 UTC by machacekondra

##### ISSUE TYPE

 - New Module Pull Request

##### COMPONENT NAME

ovirt_host_pm

##### SUMMARY

Add _ovirt_host_pm_ module to manage power management and fence agents of the oVirt hosts.

2016-10-20 12:44 UTC, machacekondra commented
@mwperina

2016-10-20 13:56 UTC, mwperina requested changes

2016-10-20 13:56 UTC, mwperina commented on cloud/ovirt/ovirt_host_pm.py
> +        default: present
Why do we need to change host status when updating fence agents? I'd prefer to update fence agents without host status change

2016-10-20 13:56 UTC, mwperina commented on cloud/ovirt/ovirt_host_pm.py
> +               I(bladecenter), I(alom), I(apc), I(eps), I(wti), I(rsb), but user can have defined custom type."
Please add all fence agents supported in 4.0:

apc, apc_snmp, bladecenter, cisco_ucs, drac5, drac7 ,eps, hpblade, ilo, ilo2, ilo3, ilo4, ilo_ssh, ipmilan, rsa, rsb, wti

2016-10-20 15:12 UTC, machacekondra commented on cloud/ovirt/ovirt_host_pm.py
> +        default: present
This is incorrect of course, I will remove it, thanks.

2016-10-20 15:33 UTC, mwperina approved these changes
Looks good to me, thanks! :+1:

2016-10-20 16:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-25 17:56 UTC, machacekondra commented
shipit

2016-10-25 22:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-08 05:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-17 14:27 UTC, ryansb commented on cloud/ovirt/ovirt_host_pm.py
> +    pass
Please check this in the module code and raise an error instead of having a NameError later in the script.

2016-11-17 14:32 UTC, mwperina commented on cloud/ovirt/ovirt_host_pm.py
> +    pass
@ryansb 
Ryan, please take a look at check_sdk() function on line 184, that's where we handle user friendly error if required SDK and its version is not present. Having this check on on place inside utils module seems to us like much better solution than do the same check in each module. Not to mention that when we will need to raise required SDK version we will do that on place

2016-11-18 14:15 UTC, merged