filesystem: get BTRFS size, add swap support
ansible/ansible-modules-extras pull request #3313
Opened 2016-10-28 08:46 UTC by romain-dartigues

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
- filesystem

##### ANSIBLE VERSION
```
ansible 2.1.2.0
```

##### SUMMARY

**Note:** I'm suggesting two changes in one PR, let me know if you want me to split them.

* 4266b1a aggregate failures (minor code design)
* b46232c get device size for btrfs which was a TODO from @alxgu set in 8d7b1b0[`L101`](https://github.com/ansible/ansible-modules-extras/commit/8d7b1b0bd6be864ef56da80b3c4bd6174c52bb54#diff-bcf0d32808383c48cad077b45e5225b9R101)
* c7ae654 introduce swap (new feature!)

I consider the swap as a new feature *and* a bug.

Before the patch (`/dev/DATA/swap` is an empty, newly created LV):
```yaml
- name: mkswap
  filesystem: fstype=swap dev=/dev/DATA/swap
```

Returned:
```
ok: [docker02] => (item={u'fs_vfstype': u'swap', u'fs_spec': u'/dev/DATA/swap', u'size': u'2G'})
```

But on the target, nothing much happened:
```console
root@docker02:~# blkid /dev/DATA/swap
root@docker02:~# file -Ls /dev/DATA/swap
/dev/DATA/swap: data
```

After the patch, the playbook says:
```
changed: [docker02] => (item={u'fs_vfstype': u'swap', u'fs_spec': u'/dev/DATA/swap', u'size': u'2G'})
```

Now on the target:
```console
root@docker02:~# blkid /dev/DATA/swap
/dev/DATA/swap: UUID="40fc8cb4-f18a-4693-85e4-189b52ff66b3" TYPE="swap"
root@docker02:~# file -Ls /dev/DATA/swap
/dev/DATA/swap: Linux/i386 swap file (new style), version 1 (4K pages), size 524287 pages, no label, UUID=40fc8cb4-f18a-4693-85e4-189b52ff66b3
```

Thanks to the existing code, the swap functionality is idempotent and when re-run will detect the FS is already a swap:
```
ok: [docker02] => (item={u'fs_vfstype': u'swap', u'fs_spec': u'/dev/DATA/swap', u'size': u'2G'})
```

The target is:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
````

##### Questions

I would like to use this opportunity to ask your opinion about a few things about some file systems:
* some don't support shrinking
* some *need* to be **mounted** in order to resize
* some *need* to be **un-mounted** in order to resize
* this plugin could check if the FS is in use before proceeding

Is it worth to make it slightly more complex and fool-proof, or is it assumed the user has the full responsibility over his doing?

2016-10-28 09:52 UTC, romain-dartigues commented
Hum, the Shippable failed jobs seems to all be caused by some kind of:

> Get https://registry-1.docker.io/v1/repositories/drydock/u14pyt/tags/prod: dial tcp: lookup registry-1.docker.io: no such host

I do not feel much concerned yet.

2016-10-28 10:25 UTC, gregdek commented
Thanks @romain-dartigues for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-10-28 10:31 UTC, romain-dartigues commented
ready_for_review because the Shippable failed jobs seems to all be caused by some kind of:

> Get https://registry-1.docker.io/v1/repositories/drydock/u14pyt/tags/prod: dial tcp: lookup registry-1.docker.io: no such host

Should I feel concerned? Please advise.

2016-10-28 14:51 UTC, romain-dartigues commented
ready_for_review

2016-11-02 08:11 UTC, alxgu commented
@romain-dartigues I would suggest to split the PR.

2016-11-02 13:19 UTC, romain-dartigues commented
@alxgu Thank you for your feedback, the PR has been split in #3345 to introduce the swap.

2016-11-06 13:51 UTC, mscherer requested changes

2016-11-06 13:51 UTC, mscherer commented on system/filesystem.py
> +def human_to_bytes(data):
There is already human_to_bytes in the basic module library, any reason to not reuse it ?

2016-11-06 18:53 UTC, romain-dartigues commented
@mscherer because I missed it (I only saw the one in `docker_common.py`), i'll correct it. Thank you for your eye.

2016-11-07 18:32 UTC, romain-dartigues commented on system/filesystem.py
> +def human_to_bytes(data):
@mscherer because I missed it (I only saw the one in `docker_common.py`), changed in 26f6435. Thank you for your eye.

Note I have to strip the letter 'i' from the string because the `human_to_bytes()` from `ansible.module_utils.basic` does not know about the IEC (ISO 80000) notation.

2016-11-07 23:25 UTC, gregdek commented
Thanks @romain-dartigues. To the current maintainers, @abulimov please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-07 21:46 UTC, tasleson commented
@romain-dartigues The module also needs a change to support re-sizing correctly for btrfs.  If you look at the code you will see that the `grow_flag` is not being utilized when the re-size command is being executed, something like this should work (not tested):

```diff
diff --git a/system/filesystem.py b/system/filesystem.py
index 10fa5af..647e2e0 100644
--- a/system/filesystem.py
+++ b/system/filesystem.py
@@ -167,7 +167,7 @@ def main():
         'btrfs' : {
             'mkfs' : 'mkfs.btrfs',
             'grow' : 'btrfs',
-            'grow_flag' : 'filesystem resize',
+            'grow_flag' : 'filesystem resize max',
             'force_flag' : '-f',
             'fsinfo': 'btrfs',
         }
@@ -190,6 +190,7 @@ def main():
     force_flag = fs_cmd_map[fstype]['force_flag']
     growcmd = fs_cmd_map[fstype]['grow']
     fssize_cmd = fs_cmd_map[fstype]['fsinfo']
+    grow_flag = fs_cmd_map[fstype]['grow_flag']
 
     if not os.path.exists(dev):
         module.fail_json(msg="Device %s not found."%dev)
@@ -217,7 +218,11 @@ def main():
             module.exit_json(changed=False, msg="%s filesystem is using the whole device %s" % (fstype, dev))
         elif fs_smaller:
             cmd = module.get_bin_path(growcmd, required=True)
-            rc,out,err = module.run_command("%s %s" % (cmd, dev))
+
+            if not grow_flag:
+                grow_flag = ""
+
+            rc,out,err = module.run_command("%s %s %s" % (cmd, grow_flag, dev))

```

2017-04-11 22:13 UTC, closed without merging