blockinfile: Fixes #1926 by comparing a marker to a whole line
ansible/ansible-modules-extras pull request #3339
Opened 2016-11-02 02:26 UTC by kokinomura

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 333f6d447b) last updated 2016/11/02 10:58:53 (GMT +900)
  lib/ansible/modules/core: (detached HEAD d2106f1c92) last updated 2016/11/02 10:59:08 (GMT +900)
  lib/ansible/modules/extras: (detached HEAD 9a01d01f78) last updated 2016/11/02 10:59:13 (GMT +900)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

Compare a marker to a whole line after stripping them based on a [comment](https://github.com/ansible/ansible-modules-extras/issues/1926#issuecomment-203070573) by @mavit.

Fixes #1926 

```

```

2016-11-03 20:58 UTC, mavit commented
For what it's worth, this looks good to me.

2016-11-07 23:25 UTC, gregdek commented
Thanks @kokinomura. To the current maintainers, @yaegashi please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-13 17:52 UTC, yaegashi requested changes
Adding `strip()` could break compatibility to existing playbooks.  Some of them might rely on preserving white spaces in marker lines.  I think simple full string matching would be safer.

needs_revision

2016-11-15 05:42 UTC, kokinomura commented
@yaegashi I've edited again as you said and rebased. Please check again.

2016-11-15 16:31 UTC, yaegashi commented
Now that looks good.  Thanks!

shipit

2016-11-15 17:25 UTC, gregdek commented
Thanks again to @kokinomura for this PR, and thanks @yaegashi for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-17 18:28 UTC, merged