Panos commit
ansible/ansible-modules-extras pull request #3384
Opened 2016-11-07 19:40 UTC by ivanbojer

ISSUE TYPE

New Module Pull Request
COMPONENT NAME

panos_commit

ANSIBLE VERSION

ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
SUMMARY

New panos module that allows user to commit current candidate configuration to the firewall

2016-11-07 21:49 UTC, ivanbojer commented
ready_for_review

2016-11-07 23:25 UTC, gregdek commented
Thanks @ivanbojer. To the current maintainers, @ivanbojer please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-24 18:39 UTC, gundalow commented on network/panos/panos_commit.py
> +            - password for authentication
`descriptions` need to be sentences (e.g. capital letters & full stops)

2016-11-24 18:39 UTC, gundalow commented on network/panos/panos_commit.py
> +            - username for authentication
Does the user need any specific permissions (if so detail), or is their only one level of user on PaloAltoNetworks equipment?

2016-11-24 18:39 UTC, gundalow commented on network/panos/panos_commit.py
> +            - interval for checking commit job
Please specify units
Interval (in seconds)..

2016-11-24 18:42 UTC, gundalow requested changes
needs_revision

2016-11-24 18:42 UTC, gundalow commented on network/panos/panos_commit.py
> +            - timeout for commit job
Please specify units

2016-11-24 18:42 UTC, gundalow commented on network/panos/panos_commit.py
> +        ip_address=dict(),
Please add `required=True,` where needed

2016-11-24 18:42 UTC, gundalow commented on network/panos/panos_commit.py
> +    if not ip_address:
If you add the `required=True,` into the `argument_spec` section you can remove these checks

2016-11-24 18:55 UTC, gundalow commented
Thanks for the module.

Not sure if you aware, we have a Network Working Group, check out https://github.com/ansible/community/blob/master/MEETINGS.md for details

1) What is needed to make this module idempotent (e.g. support check mode)
http://docs.ansible.com/ansible/dev_guide/developing_modules.html#check-mode

2) For us to accept new (or updated) network modules into 2.3 we require functional test to be added
https://github.com/ansible/ansible/blob/devel/test/integration/README.md#network-tests has more details.

If you need help with this feel free to message me directly `gundalow`  on FreeNode IRC. I'm in the UK, though IRC is always running, so feel free to leave me a message.

2017-01-02 15:53 UTC, closed without merging