Fix issue in adding RAW disk in block storage domain
ansible/ansible-modules-extras pull request #3432
Opened 2016-11-11 12:11 UTC by nijinashok

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
Ovirt

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel)
```

##### SUMMARY
Ovirt won't allow to add RAW sparse disk in block storage domain and is only available in file based storage domain. By default, sparse option is true in ovirt. So the raw disk creation in a block storage domain will fail with error "Disk configuration (RAW Sparse) is incompatible with the storage domain type". 

The commit adds sparse option where user can pass it as "True/False". So while creating RAW disk in block storage domain, we can pass "sparse = True" to make it work.

2016-11-11 17:25 UTC, gregdek commented
Thanks @nijinashok. To the current maintainers, @machacekondra please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-15 09:53 UTC, machacekondra requested changes
Thank you very much for the fix. Can you please check out my comments?

2016-11-15 09:53 UTC, machacekondra commented on cloud/ovirt/ovirt_disks.py
> +            equal(self._module.params.get('sparse'), entity.sparse) and
Currently it's not possible to change allocation policy of the disk in API. so this shouldn't be here, as we can't update it.

2016-11-15 09:53 UTC, machacekondra commented on cloud/ovirt/ovirt_disks.py
> +        sparse=dict(default=None, type='bool'),
On line 244 there is ```allocation_policy``` parameter, which I forgot to implement, which should handle this action. Can you please remove it?

2016-11-15 09:53 UTC, machacekondra commented on cloud/ovirt/ovirt_disks.py
> +            - "I(True) create disk with sparse allocation. By default ovirt-engine create sparse allocated disk"
Can you please change to following description:

- If (True) disk will by createad as sparse, so space will be allocated for the volume as needed, also known as I(thin provision).
- If (False) storage will be allocated right away, also known as I(preallocated).
- Note that this option isn't idempotent as it's not currently possible to change allocation policy of disk via API.

2016-11-15 10:12 UTC, machacekondra commented
Taking back my comments. There shouldn't be any ```sparse``` parameter, but we should send ```sparse = True``` or ```sparse = False``` depend on the format parameter. So if user will send the ```raw``` we will send ```sparse=False``` and if user specify ```cow``` we will send ```sparse=True```.

Also we should change documentation of ```format``` parameter accordingly:

    - Specify format of the disk.
    - If (cow) format is used, disk will by created as sparse, so space will be allocated for the volume as needed, also known as I(thin provision).
    - If (raw) format is used, disk storage will be allocated right away, also known as I(preallocated).
    - Note that this option isn't idempotent as it's not currently possible to change format of the disk via API.

2016-11-15 10:14 UTC, machacekondra commented
Also if you can please remove checking of ```format``` parameter in ```update_check``` method. As it don't make any sense. And also as previously noted please remove ```allocation_policy``` parameter. Do you have time to do it? If not I will do it.

2016-11-16 04:08 UTC, nijinashok commented
Thanks a lot for reviewing the request. I have made changes as per your suggestion.

2016-11-16 17:24 UTC, machacekondra commented
Thank you, looks good to me. Maybe I would replace ```False if self._module.params.get('format') == 'raw' else True``` with ```self._module.params.get('format').lower() != 'raw'```, but not critical I guess.

@mperina Can you please review? As oVirt support following matrix:

file based storage:
 - RAW preallocated
 - RAW sparse
 - qcow2 sparse

block storage:
 - RAW preallocated
 - qcow2 sparse

So in my opinion we should create always this options:
  - RAW preallocated
  - qcow2 sparse

unless oVirt will support more.

2016-11-16 18:44 UTC, machacekondra commented
@mwperina

2016-11-17 09:59 UTC, machacekondra commented
shipit

2016-11-17 11:25 UTC, gregdek commented
Thanks again to @nijinashok for this PR, and thanks @machacekondra for reviewing. Marking for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-17 13:52 UTC, mwperina approved these changes
:+1:

2016-11-17 14:24 UTC, merged