Use native YAML
ansible/ansible-modules-extras pull request #3435
Opened 2016-11-11 17:12 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
cloud/amazon/route53

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

2016-11-11 17:25 UTC, gregdek commented
Thanks @Fale. To the current maintainers, @minichate please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-11 22:39 UTC, gundalow requested changes

2016-11-11 22:39 UTC, gundalow commented on cloud/amazon/route53_zone.py
> +    var: zone_out
I'd need to check, though I think this should have quotes and double curly braces.

2016-11-11 23:51 UTC, Fale commented on cloud/amazon/route53_zone.py
> +    var: zone_out
If you want to print a variable in "msg" yes, in "var" you should not. We can discuss on the "safety" of this feature. http://docs.ansible.com/ansible/debug_module.html

2016-11-13 09:12 UTC, gundalow commented
@fale thanks, I was remembering `msg` v `var`
If there is any extra discussion needed that can be done in one of the public IRC meetings.

2016-11-13 09:13 UTC, gundalow approved these changes

2016-11-13 09:13 UTC, merged