Use native YAML
ansible/ansible-modules-extras pull request #3440
Opened 2016-11-11 17:32 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
system/crypttab

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

2016-11-11 22:36 UTC, gundalow requested changes

2016-11-11 22:36 UTC, gundalow commented on system/crypttab.py
> +  crypttab:
I wonder if it's worth adding a comment to remind people to quote `opts` if it contains `:`, what do you think?

2016-11-11 23:25 UTC, gregdek commented
Thanks @Fale. To the current maintainers, @groks please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-13 09:05 UTC, gundalow commented
needs_revision

2016-11-13 11:25 UTC, gregdek commented
Thanks @Fale for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-28 23:26 UTC, gregdek commented
@Fale A friendly reminder: this pull request has been marked as needing your action. If you still believe that this PR applies, and you intend to address the issues with this PR, just let us know in the PR itself and we will keep it open pending your changes. When you do address the issues, please respond with ready_for_review in your comment, so that we can notify the maintainer.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-30 15:34 UTC, Fale commented
What do you think?

2016-11-30 17:11 UTC, gundalow approved these changes

2016-11-30 17:11 UTC, merged

2016-11-30 17:11 UTC, gundalow commented
Merged, thanks