Windows Shortcut on windows host
ansible/ansible-modules-extras pull request #3552
Opened 2016-11-28 07:30 UTC by Rajeshkumar90

ISSUE TYPE

New Module Pull Request
COMPONENT NAME

Adding shortcut to windows host

ANSIBLE VERSION

ansible 2.1.2.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides

SUMMARY

Adding windows shortcut to the windows host

Example :
win_shortcut:
src: 'C:\Program Files\Notepad++\notepad++.exe'
dest: 'C:\Users\588378\Desktop\notepad++.lnk'

2016-11-28 08:16 UTC, jhawkesworth commented on windows/win_shortcut.ps1
> +{
I think it would be better if this was a try {  ...  } catch {   .. }} block so any exceptions can be caught and returned using Fail-Json.

2016-11-28 08:19 UTC, jhawkesworth commented on windows/win_shortcut.py
> +    - Uses .net Environment to set path environment variables and can set at User, Machine and Process level.
Looks like description needs updating.

2016-11-28 08:20 UTC, jhawkesworth commented
Almost there, just a couple of little things to address (see inline comments).
Many thanks,
Jon

2016-11-28 09:43 UTC, Rajeshkumar90 commented on windows/win_shortcut.py
> +    - Uses .net Environment to set path environment variables and can set at User, Machine and Process level.
Updated with new file

2016-11-28 09:59 UTC, Rajeshkumar90 reviewed
Added try and catch for ps file

2016-11-28 09:59 UTC, Rajeshkumar90 commented on windows/win_shortcut.ps1
> +{
added try and catch
tested in env

2016-11-28 11:25 UTC, gregdek commented
Thanks @Rajeshkumar90 for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-01 18:11 UTC, nitzmahone requested changes
Biggest thing is ensuring it properly updates an existing shortcut. Couple other little things that will make the code a lot smaller.

2016-12-01 18:11 UTC, nitzmahone commented on windows/win_shortcut.py
> +    dest: 'C:\\users\\Test\\Desktop\\Firefox.exe'
We're trying to standardize on unquoted, unescaped paths for Windows module docs going forward, so these should be like `src: C:\Program Files\Mozilla Firefox\Firefox.exe`

2016-12-01 18:11 UTC, nitzmahone commented on windows/win_shortcut.ps1
> +If ($TargetFile -eq $FALSE)
Use -failifempty arg to Get-Attr and you can get rid of this

2016-12-01 18:11 UTC, nitzmahone commented on windows/win_shortcut.ps1
> +If ($ShortcutFile -eq $FALSE)
Same- use -failifempty.

2016-12-01 18:11 UTC, nitzmahone commented on windows/win_shortcut.ps1
> +If(($TargetFile -or $ShortcutFile) -eq $null)
This will be unnecessary with -failifempty usage above

2016-12-01 18:11 UTC, nitzmahone commented on windows/win_shortcut.ps1
> + if((Test-Path  $TargetFile ) -and (Test-Path $ShortcutFile))
This isn't fully testing the change conditions. What if the target path is different than the existing shortcut? The module should be able to handle this case easily (luckily, CreateShortcut also allows you to inspect/edit an existing shortcut, so should be very easy to add this behavior).

2016-12-01 19:45 UTC, nitzmahone commented
Only other comment: for common UI sake with the *nix file module, (and how small the required code is), adding this to win_file as `state: shortcut` might make more sense than a standalone module...

2016-12-01 19:56 UTC, dagwieers commented
Oh wait, I have my own implementation of this that I hadn't shared yet.

https://github.com/crombeen/ansible/blob/master/library/win_shortcut.ps1

You can set a shortcut, change the (visible) name of the link and add an icon. I don't think we want this to be part of the win_file module as well. A shortcut is certainly not the same as a symlink on Linux.

2016-12-01 19:57 UTC, nitzmahone commented
@dagwieers Good point- if you take it to the logical conclusion by adding all the other shortcut properties, we definitely don't want all that in win_file. OK, nevermind on that part. :)

2016-12-01 20:00 UTC, dagwieers commented
Shall I add my win_shortcut implementation as an alternative in a PR ?

2016-12-01 20:03 UTC, nitzmahone commented
@dagwieers Yours doesn't look like it fully handles change detection on the various properties- that'd be a merge blocker for me personally. I figure it's trivial to add the other properties to this one later once the target change detection is in place.

2016-12-01 20:04 UTC, dagwieers commented
True, that's the reason why I hadn't added it :-)

2016-12-02 12:07 UTC, Rajeshkumar90 commented
'ready_for_review'

2017-02-03 13:07 UTC, jhawkesworth commented
closing alternative win_shortcut module has now been merged.

2017-02-03 13:07 UTC, closed without merging