ovirt_vms: Add new cloud_init_nics parameter (#3447)
ansible/ansible-modules-extras pull request #3557
Opened 2016-11-28 18:24 UTC by machacekondra

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

ovirt_vms

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

#3447 

```

```

2016-11-28 23:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-29 08:03 UTC, machacekondra commented
shipit

2016-11-29 11:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-11-29 13:25 UTC, machacekondra commented
@mwperina @ryansb

2016-11-30 14:42 UTC, mwperina requested changes

2016-11-30 14:42 UTC, mwperina commented on cloud/ovirt/ovirt_vms.py
> +            - "This option is used, when user need to setup more network interfaces via cloud init."
... when user needs ...

2016-11-30 14:42 UTC, mwperina commented on cloud/ovirt/ovirt_vms.py
> +            - "C(nic_boot_protocol) - Set boot protocol of the network interface of Virtual Machine. Can be one of None, DHCP or Static."
Maybe it's better to display value in lowercase as values are not case sensitive: none, dhcp, static

2016-12-05 17:34 UTC, merged