Add oVirt ovirt_affinity_labels and ovirt_affinity_labels_facts modules
ansible/ansible-modules-extras pull request #3570
Opened 2016-11-30 15:21 UTC by machacekondra

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

- ovirt_affinity_labels 
- ovirt_affinity_labels_facts

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

This modules add support to work with oVirt affinity labels.

2016-11-30 15:24 UTC, machacekondra commented
@mwperina @ryansb

2016-11-30 16:01 UTC, mwperina requested changes

2016-11-30 16:01 UTC, mwperina commented on cloud/ovirt/ovirt_affinity_labels.py
> +    - "This module manage affinity labels in oVirt. It can also manage asignments
asignments -> assignments

2016-11-30 16:01 UTC, mwperina commented on cloud/ovirt/ovirt_affinity_labels.py
> +       of those lables to hosts and VMs."
lables -> labels

2016-11-30 16:21 UTC, mwperina approved these changes
Looks good to me! :+1:

2016-11-30 17:25 UTC, gregdek commented
Thanks again to @machacekondra. This module is going into community review.

We notice that you are one of the maintainers (@machacekondra) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-05 12:45 UTC, machacekondra commented
shipit

2016-12-05 13:44 UTC, mwperina approved these changes
:+1:

2016-12-05 17:25 UTC, gregdek commented
Thanks @machacekondra. Since you are one of the maintainers (@machacekondra) of this module and you commented with "shipit", we are marking this PR for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-05 17:33 UTC, merged