Native YAML - cloud/misc
ansible/ansible-modules-extras pull request #3615
Opened 2016-12-01 17:19 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
cloud/misc/*

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

@gundalow

2016-12-01 17:25 UTC, gregdek commented
Thanks @Fale for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with 'needs_revision' or merge as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-01 19:32 UTC, gundalow requested changes
needs_revision

2016-12-01 19:32 UTC, gundalow commented on cloud/misc/proxmox.py
> +EXAMPLES :  '''
Looks like there is an extra space in there
```
2016-12-01 17:25:09 + python2.6 -m compileall -fq .
2016-12-01 17:25:13 Compiling ./cloud/misc/proxmox.py ...
2016-12-01 17:25:13 SyntaxError: ('invalid syntax', ('./cloud/misc/proxmox.py', 177, 10, "EXAMPLES :  '''\n"))
```

2016-12-01 23:25 UTC, gregdek commented
Thanks @Fale for this PR. This PR requires revisions, either because it fails to build or by reviewer request. Please make the suggested revisions. When you are done, please comment with text 'ready_for_review' and we will put this PR back into review.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-02 14:49 UTC, gundalow approved these changes

2016-12-02 14:49 UTC, merged