Native YAML - files/blockinfile.py
ansible/ansible-modules-extras pull request #3630
Opened 2016-12-02 12:56 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
files/*

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

@gundalow

2016-12-02 15:49 UTC, gundalow requested changes

2016-12-02 15:49 UTC, gundalow commented on files/blockinfile.py
> -      - { name: host1, ip: 10.10.1.10 }
I'm going to say that rewriting the `write_items` section here decreases readability.

Therefore closing this PR

2016-12-02 17:25 UTC, gregdek commented
Thanks @Fale. To the current maintainers, @yaegashi please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-04 10:51 UTC, gundalow approved these changes

2016-12-04 10:53 UTC, merged