Native YAML - monitoring/boundary_meter
ansible/ansible-modules-extras pull request #3636
Opened 2016-12-02 16:25 UTC by Fale

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
monitoring/boundary_meter

##### ANSIBLE VERSION
```
2.2
```

##### SUMMARY
Make YAML code use the native style

@gundalow

2016-12-02 17:25 UTC, gregdek commented
Thanks @Fale. To the current maintainers, @ccollicutt please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit', 'needs_revision' or 'close_me' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-04 10:57 UTC, gundalow requested changes
needs_revision 

Not your bug, however I noticed that the use of `_` was inconsistent in the examples.

2016-12-04 10:57 UTC, gundalow commented on monitoring/boundary_meter.py
> +    api_key: BBBBBB
Original example is wrong, it's `apikey`

2016-12-04 10:57 UTC, gundalow commented on monitoring/boundary_meter.py
> +    api_key: BBBBBB
`apikey`

2016-12-04 11:01 UTC, Fale commented
Nice catch!

2016-12-06 21:52 UTC, closed without merging