Add module for AWS IAM Identity Federation (SAML) management
ansible/ansible-modules-extras pull request #3645
Opened 2016-12-05 00:17 UTC by aidan-

##### ISSUE TYPE
 - New Module Pull Request

##### COMPONENT NAME
cloud/amazon/iam_saml_federation.py

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
Adds support for managing AWS IAM Identity Federation (SAML) providers.
Supports check_mode.

2016-12-05 05:25 UTC, gregdek commented
Thanks @aidan- for this new module. When this module receives 'shipit' comments from two community members and any 'needs_revision' comments have been resolved, we will mark for inclusion.

[This message brought to you by your friendly Ansibull-bot.]

2016-12-05 16:13 UTC, ryansb requested changes

2016-12-05 16:13 UTC, ryansb commented on cloud/amazon/iam_saml_federation.py
> +    saml_metadata_document: >
Can you also put a comment in here about what the `>` means when opening a text block? Something to the effect of:
```
# the > here opens an indented block, so no escaping/quoting is needed when in the indentation level under this key
```

2016-12-05 16:13 UTC, ryansb commented on cloud/amazon/iam_saml_federation.py
> +          resp = self.conn.create_saml_provider(SAMLMetadataDocument=metadata, Name=name)
Can you return the provider ARN in both the update & create cases? `boto3` returns them as `SAMLProviderArn` on the response object. http://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.create_saml_provider

2016-12-05 16:13 UTC, ryansb commented on cloud/amazon/iam_saml_federation.py
> +      - An  XML  document  generated by an identity provider (IdP) that supports SAML 2.0.
Can you link to the AWS docs that explain this XML doc? The only reference I can find is docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html

2016-12-05 16:15 UTC, ryansb commented
Also, it appears this file is indented with 2-space tabs. The Ansible style guides follow the PEP8-standard 4-space indentation. Can you please switch to that style?

2016-12-06 01:21 UTC, aidan- commented
Thank you for the feedback @ryansb, those issues have now been fixed.

2016-12-09 16:09 UTC, closed without merging